"""
Django settings for early_dot project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
from datetime import timedelta



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 로그인 이후 기본 토큰 유효시간 5분에서 1시간으로 반영
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),   # ← 액세스 1시간
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),   # ← 기본 유지(원하면 조절)
    # 아래는 기본값과 동일하지만, 명시해두면 팀원 이해에 좋음
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# 사용자가 올린 파일(사진, 인증서 등)이 저장되는 디렉토리의 절대 경로
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# MEDIA 파일을 처리하는 URL
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# .env 파일 위치를 기반으로 환경 설정 로드
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# 💡 수정 코드: BASE_DIR(backend의 상위, 즉 프로젝트 루트)를 기준으로 .env 파일을 찾도록 수정
environ.Env.read_env(env_file=BASE_DIR / '.env') # BASE_DIR은 /app/early_dot 에 해당

# 추후에 서버 배포용으로 분리
DJANGO_ENV = env("DJANGO_ENV", default="local")


# SECRET_KEY와 DEBUG를 환경 변수에서 가져옵니다.
SECRET_KEY = env('Django_SECRET_KEY')
DEBUG = env('DEBUG')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',      # DRF 기본
    'rest_framework_simplejwt',  # JWT 인증
    'corsheaders',        # CORS 설정을 위해 필요

    # 💡 새로 만든 앱 4개 등록
    'users',
    'diagnosis',
    'dashboard',
    'admin_tools',
]

#SITE_ID 설정 추가 (django.contrib.sites를 사용하면 필수)
SITE_ID = 1

# 커스텀 유저 사용
AUTH_USER_MODEL = 'users.Users'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <--- 이 줄을 추가하거나 위치 조정
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'early_dot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'early_dot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 시퀄 닫아둠
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# 또는 환경 변수를 직접 사용하는 경우 (env 라이브러리를 사용한다면 위 코드가 권장됨)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='3306'),
        # 기타 MySQL 설정 (CHARSET, COLLATION 등)
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    #{ 이거 디장고 자체적으로 비번 제약 걸어놓는 부분인데, 제약이 너무 빡세서 일단 빼놓음
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #},
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # 🔴 이 부분을 임시로 주석 처리하거나 AllowAny로 변경
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated', # 🚨 주석 처리 또는 제거
        'rest_framework.permissions.AllowAny',  # 💡 임시로 AllowAny로 변경
    ]
}

# -------------------------------------------------------------------
# 💡 리액트 FE + Docker 컨테이너 + Mac 로컬 네트워크 CORS 설정
# -------------------------------------------------------------------

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "0.0.0.0",    # Docker 외부 접근 허용
    "django",     # Docker 네트워크 내부 접근용
    # Mac 로컬 네트워크 접근 허용 (맥북 이름 부분은 각자 환경에 맞게)
    "sondongbin-ui-MacBookPro.local",
]

# 개발 중에는 모든 오리진 허용 (편의성)
CORS_ALLOW_ALL_ORIGINS = True

# 명시적 오리진 허용 (배포 시에만 True→False 바꾸고 이 목록만 남기면 됨)
CORS_ALLOWED_ORIGINS = [
    # React 로컬 개발 서버 (팀원들이 자기 로컬에서 접속)
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",

    # Docker 내부 네트워크 (프론트/백/모델 서버 간 통신)
    "http://frontend:3000",
    "http://frontend:5173",
    "http://fastapi:8001",

    # Mac 네트워크 이름 접근 (같은 와이파이 내 다른 PC에서 접근)
    "http://sondongbin-ui-MacBookPro.local:3000",
    "http://sondongbin-ui-MacBookPro.local:5173",
]

# CSRF 신뢰 오리진 (axios 등으로 POST 전송 시 403 방지)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://0.0.0.0:8000",
    "http://django:8000",
    "http://sondongbin-ui-MacBookPro.local:3000",
    "http://sondongbin-ui-MacBookPro.local:5173",
]

# 추후 배포용 서버분리를 위함
if DJANGO_ENV == "prod":
    DEBUG = False
    CORS_ALLOW_ALL_ORIGINS = False
    ALLOWED_HOSTS = ["your-production-domain.com"]
    CSRF_TRUSTED_ORIGINS = ["https://your-production-domain.com"]
