"""
Django settings for early_dot project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# =============================================
# 📄 .env 환경 변수 로드
# =============================================
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(
    env_file=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
)

SECRET_KEY = env("Django_SECRET_KEY")
DEBUG = env("DEBUG")

# =============================================
# ⚙️ 앱 설정
# =============================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # 🔹 외부 라이브러리
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",

    # 🔹 로컬 앱
    "users",
    "diagnosis",
    "dashboard",
    "admin_tools",
]

#SITE_ID 설정 추가 (django.contrib.sites를 사용하면 필수)
SITE_ID = 1
AUTH_USER_MODEL = "users.Users"

# 커스텀 유저 사용
AUTH_USER_MODEL = 'users.Users'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",          # ✅ 반드시 가장 위
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'early_dot.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "early_dot.wsgi.application"

# =============================================
# 🗄 데이터베이스 설정
# =============================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST", default="127.0.0.1"),
        "PORT": env("DB_PORT", default="3306"),
    }
}

# =============================================
# 🔐 비밀번호 검증
# =============================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    #{ 이거 디장고 자체적으로 비번 제약 걸어놓는 부분인데, 제약이 너무 빡세서 일단 빼놓음
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #},
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# =============================================
# 🌐 국제화 설정
# =============================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True

USE_TZ = True

# =============================================
# 📦 정적 파일 설정
# =============================================
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================
# 🔑 REST Framework 기본 설정
# =============================================
REST_FRAMEWORK = {
    # 🔴 이 부분을 임시로 주석 처리하거나 AllowAny로 변경
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated', # 🚨 주석 처리 또는 제거
        'rest_framework.permissions.AllowAny',  # 💡 임시로 AllowAny로 변경
    ]
}

# -------------------------------------------------------------------
# 💡 리액트 FE 연동을 위한 CORS 설정
# -------------------------------------------------------------------

# [기본값: 로컬만 허용]
#ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]    #<- mac 기준으로 이거 주석 풀고, 아래 주석 달면 됨.
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# 모든 호스트를 허용합니다 (배포 시에는 특정 도메인으로 제한해야 합니다).
CORS_ALLOW_ALL_ORIGINS = True   # 개발 한정임
#CORS_ALLOW_ALL_ORIGINS = False

# 로컬 FE 오리진만 허용
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # 네트워크(IP) 바뀌어도 접속되게 하려면 .local 추가(주석 해제)
    # sondongbin-ui-MacBookPro 으로 되어 있는 부분이 mac 사용자의 macbook 이름이 들어가면 됨,
    #"http://sondongbin-ui-MacBookPro.local:3000",
    #"http://sondongbin-ui-MacBookPro.local:5173",
]

# CSRF 신뢰 오리진
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # 네트워크(IP) 바뀌어도 접속되게 하려면 .local 추가(주석 해제)
    # sondongbin-ui-MacBookPro 으로 되어 있는 부분이 mac 사용자의 macbook 이름이 들어가면 됨,
    #http://sondongbin-ui-MacBookPro.local:3000",
    #http://sondongbin-ui-MacBookPro.local:5173",
]