# Generated by Django 5.2.7 on 2025-10-25 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('요청중', '요청중'), ('확인 완료', '확인 완료')], default='요청중', max_length=20)),
                ('doctor_risk_level', models.CharField(blank=True, choices=[('소견 대기', '소견 대기'), ('즉시 주의', '즉시 주의'), ('경과 관찰', '경과 관찰'), ('정상', '정상')], max_length=20, null=True)),
                ('doctor_note', models.TextField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_checks_assigned', to='users.doctors')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_check', to='diagnosis.results')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_checks_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '후속 조치 요청',
                'db_table': 'followup_check',
            },
        ),
        migrations.CreateModel(
            name='FollowUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('요청중', '요청중'), ('확인 완료', '확인 완료')], max_length=20)),
                ('changed_by', models.CharField(max_length=10)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.followupcheck')),
            ],
            options={
                'verbose_name': '후속 조치 기록',
                'db_table': 'followup_history',
            },
        ),
    ]
