# Generated by Django 5.2.7 on 2025-10-25 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(max_length=20)),
                ('rep_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '질병 정보',
                'db_table': 'disease_info',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_storage_path', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('folder_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('body_part', models.CharField(max_length=50)),
                ('capture_date', models.DateTimeField(auto_now_add=True)),
                ('symptoms_itch', models.TextField(blank=True, null=True)),
                ('symptoms_pain', models.TextField(blank=True, null=True)),
                ('symptoms_color', models.TextField(blank=True, null=True)),
                ('symptoms_infection', models.TextField(blank=True, null=True)),
                ('symptoms_blood', models.TextField(blank=True, null=True)),
                ('onset_date', models.CharField(max_length=50)),
                ('meta_age', models.IntegerField()),
                ('meta_sex', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '촬영 이미지',
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.CharField(max_length=10)),
                ('class_probs', models.JSONField()),
                ('grad_cam_path', models.ImageField(blank=True, null=True, upload_to='cams/')),
                ('vlm_analysis_text', models.TextField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='results', to='diagnosis.diseaseinfo')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='diagnosis.photos')),
            ],
            options={
                'verbose_name': '진단 결과',
                'db_table': 'results',
            },
        ),
    ]
