# Generated by Django 5.2.7 on 2025-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='hair',
            field=models.CharField(default='N', max_length=20),
            preserve_default=False,
        ),
    ]
