# Generated by Django 5.2.8 on 2025-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='hair',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
