# Generated by Django 5.2.8 on 2025-11-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_remove_results_vlm_analysis_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='hair',
        ),
    ]
