# Generated by Django 5.2.7 on 2025-10-25 02:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('family_history', models.CharField(default='모름', max_length=10)),
                ('is_doctor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '일반 사용자/환자',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_path', models.ImageField(blank=True, null=True, upload_to='certs/')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '의사 정보',
                'db_table': 'doctors',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='doctor',
            field=models.ForeignKey(blank=True, db_column='doctor_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.doctors'),
        ),
    ]
