# Generated by Django 5.2.8 on 2025-11-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='가입 거절 사유', null=True),
        ),
    ]
